### ISSUE TITLE
Incorrect HDR conversion result

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [natural-harmonia-gropius/mpv-config#14]
https://github.com/Natural-Harmonia-Gropius/mpv_config/issues/11#issuecomment-1407580910

**Comment by Natural-Harmonia-Gropius** [comment]
@pintassilgo Let's continue to look at the issue here.

Can you share the screenshot of stats page? For my config, press `tab` `2`.
I only have a windows PC and I can get same results to you under vo=gpu.

vo=gpu-next
![image](https://user-images.githubusercontent.com/50797982/215387463-82e05e91-2d2c-418f-ac60-6039228ccfa4.png)
vo=gpu
![image](https://user-images.githubusercontent.com/50797982/215387577-3fb70118-72de-4ec9-b162-667a816c202c.png)

**Comment by Natural-Harmonia-Gropius** [comment]
I need the screenshot of console, should be some error there.

**Comment by Natural-Harmonia-Gropius** [comment]
That `unrecognized command` is, try newer version, or report an issue to mpv.

**Comment by Natural-Harmonia-Gropius** [comment]
Then I think you need to upgrade libplacebo, but I don't know how to do it.
https://github.com/haasn/libplacebo

**Comment by Natural-Harmonia-Gropius** [comment]
It's a feature of libplacebo (gpu-next), you have the latest mpv and libplacebo, they should support this.
https://libplacebo.org/custom-shaders/#param-name

**Comment by Natural-Harmonia-Gropius** [comment]
[https://github.com/mpv-player/mpv/blob/master/video/out/gpu](https://github.com/mpv-player/mpv/blob/master/video/out/gpu/user_shaders.c) is vo=gpu, of course not support.
the shader is sent to libplacebo.so or something like this, process not be done in mpv.

**Comment by Natural-Harmonia-Gropius** [comment]
Just follow the mpv issue template.
Remove `#` and run mpv with that av1 video, log file will appear in protable_config.
![image](https://user-images.githubusercontent.com/50797982/215406592-4cb1b1ce-b450-4f72-9da7-b22533d182d7.png)

Title:
gpu_next: //!PARAM in shader can't be parsed.

Content:
![image](https://user-images.githubusercontent.com/50797982/215406182-4370b14d-64ec-4184-8c88-abb485f9c042.png)
Your log here.

**Comment by Natural-Harmonia-Gropius** [comment]
No idea with Linux, I would suggest waiting for the next stable release.

For me, windows have an all-in-one exe nightly build. https://github.com/shinchiro/mpv-winbuild-cmake/releases
