### ISSUE TITLE
Dither choice

### ISSUE THREAD

**Issue by danbezerra** [natural-harmonia-gropius/mpv-config#18]
Quick question - I noticed that you don't have any dither methods defined in your config file, other than the image profile. Is this because you handle it via the shaders as well?

Thanks!

**Comment by natural-harmonia-gropius** [comment]
> Select dithering algorithm (default: fruit). (Normally, the --dither-depth option controls whether dithering is enabled.)

error-diffusion cost too much, but it has better quality, so only use it for still image.

**Comment by danbezerra** [comment]
Ah, makes sense. I missed the info about dither-depth controlling dithering on/off. Thanks!
