### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Ognisty321** [natural-harmonia-gropius/mpv-config#19]
Hey, any chance that you could make the UI english?

Idk which option is for what
![sTlRnfC 1](https://user-images.githubusercontent.com/32206254/227574048-e86aac1a-adc5-4d25-a3fe-e2d6587e97d3.png)

**Comment by natural-harmonia-gropius** [comment]
I will create an english branch, probably tomorrow.

**Comment by natural-harmonia-gropius** [comment]
~~https://github.com/natural-harmonia-gropius/mpv-config/tree/intl-en_us~~

~~Do you need to change some wording?~~

Re-added at https://github.com/natural-harmonia-gropius/mpv-config/pull/20

**Comment by natural-harmonia-gropius** [comment]
To use Non-Chinese, you need to delete or edit:

1. `custom.json`
2. `script-opts-add=uosc-languages=` in mpv.conf
3. `slang=` in mpv.conf
