### ISSUE TITLE
d3d11 validation is spamming

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [natural-harmonia-gropius/mpv-config#22]
see: https://github.com/mpv-player/mpv/issues/11561#issuecomment-1505196252

Not happened to me.

- [ ] Check ravu?
- [ ] Other than ravu?

**Comment by kasper93** [comment]
Actually, I had the same with my config. D3D11 validation enforces io/out layout compatibility between vertex/fragment shaders. Simply changing bind order fixes the issue.

See here:
KrigBilateral.glsl: https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637?permalink_comment_id=4546672#gistcomment-4546672
SSimDownscaler.glsl: https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10?permalink_comment_id=4546678#gistcomment-4546678

I put more info in the comments there, but it is mostly cosmetic change.
