### ISSUE TITLE
流式传输菜单语言改变

### ISSUE THREAD

**Issue by 2607627233** [natural-harmonia-gropius/mpv-config#24]
使用流式传输的时候 osc和右键menu会变成英语
![捕获](https://github.com/natural-harmonia-gropius/mpv-config/assets/43110396/147a7580-5c90-41a9-852f-ed507222ac8f)

**Comment by natural-harmonia-gropius** [comment]
播放本地文件时是正常的？

可以具体描述下“流式传输”的操作步骤吗？

我这边正常
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/d85656d6-2699-41e0-a0ec-b38b82d6a26c)

**Comment by 2607627233** [comment]
> 播放本地文件时是正常的？
> 
> 可以具体描述下“流式传输”的操作步骤吗？
> 
> 我这边正常 ![image](https://user-images.githubusercontent.com/50797982/251946831-d85656d6-2699-41e0-a0ec-b38b82d6a26c.png)

我播放的是阿里云盘，目前发现是播放的时候slang这个指令不知道为什么没有生效，在uosc,conf里把它去掉，只留下zh-hans之后就没问题了。
