### ISSUE TITLE
how to append clipboard/URL to playlist?

### ISSUE THREAD

**Issue by candrapersada** [natural-harmonia-gropius/mpv-config#26]

**Comment by natural-harmonia-gropius** [comment]
Personally I use `mpv <path | url>` in terminal (system's) or drag and drop.

You can try scripts below.
https://github.com/tsl0922/mpv-menu-plugin
https://github.com/CogentRedTester/mpv-clipboard/blob/master/clipboard.lua
https://github.com/Eisa01/mpv-scripts#smartcopypaste
