### ISSUE TITLE
Auto update via GitHub Actions

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [natural-harmonia-gropius/mpv-config#27]
**Uncovered:** 

- [x] [igv/FSRCNNX](https://github.com/igv/FSRCNN-TensorFlow/releases)
- [x] [igv/gist](https://gist.github.com/igv)
- [x] [natural-harmonia-gropius/hdr-toys](https://github.com/natural-harmonia-gropius/hdr-toys) | shaders/hdr-toys -> portable_config/shaders/hdr-toys
- [x] [natural-harmonia-gropius/uosc](https://github.com/natural-harmonia-gropius/uosc) - forked from [tomasklaen/uosc](https://github.com/tomasklaen/uosc) | src/uosc -> portable_config/scripts/uosc
- ~[ ] [haasn/libplacebo.org](https://libplacebo.org/custom-shaders/#full-example)~

**Comment by Yunuuuu** [comment]
It'll be better if https://github.com/natural-harmonia-gropius/mpv-config/blob/master/.github/workflows/update.yml can use the default branch

**Comment by Yunuuuu** [comment]
This can be helpful: https://github.com/knutkirkhorn/default-branch

**Comment by natural-harmonia-gropius** [comment]
Done

**Comment by natural-harmonia-gropius** [comment]
bot disappeared after rebase, interesting.
