### ISSUE TITLE
Washed

### ISSUE THREAD

**Issue by vmv** [natural-harmonia-gropius/mpv-config#3]
The image colors are so washed.. so ugly.
Comparing with Movies & TV from Microsoft with default settings.. the differences are sky high, in the image quality.
Can there be tests between these two players for the best output?
Thanks!

**Comment by natural-harmonia-gropius** [comment]
I don't see anything wrong with https://github.com/vmv/mpv_config/blob/main/mpv.conf.

How about delete folling part?
![image](https://user-images.githubusercontent.com/50797982/188288992-e00f7cfc-7fc3-4c86-b8f3-7d0cd7bf67df.png)
