### ISSUE TITLE
计算sdr每帧"亮度"

### ISSUE THREAD

**Issue by hooke007** [natural-harmonia-gropius/mpv-config#30]
不知道你有无兴趣研究这个略奇怪的着色器的实现。
原始请求人（不是我）是受到了图片浏览器等其它软件启示 —— 能根据直方图自动调节亮度/对比达到较好的观感。正在寻找播放器中有无实现类似的功能的方法。
https://ffmpeg.org/ffmpeg-filters.html#histeq 测下来暂不理想

或者说你的hdr-toy经过微调可能也能应用在sdr上？

**Comment by natural-harmonia-gropius** [comment]
最原始的思路是把整张图转成灰度后加权计算平均数或者中位数对齐0.18

> 你的hdr-toy经过微调可能也能应用在sdr上

我周末（也可能下周末）有空试试

> 图片浏览器等其它软件启示 —— 能根据直方图自动调节亮度/对比达到较好的观感

具体是什么图片浏览器？

**Comment by hooke007** [comment]
已pin原求助人。

>> 具体是什么图片浏览器？
>
> 一些国产播放器自带的“画质增强功能”
> xnview classic版 图像-调整-正常化

<img width=400 src="https://github.com/natural-harmonia-gropius/mpv-config/assets/41094733/83f5557a-85ba-45a4-8edb-7ee33e5750cb">
<img width=400 src="https://github.com/natural-harmonia-gropius/mpv-config/assets/41094733/f391e426-70ff-4bbf-9fc3-f0408082e5f1">

我在mp版本里没找到这个功能但是有个看起来近似的(图像-调整-色阶)
<img width=400 src="https://github.com/natural-harmonia-gropius/mpv-config/assets/41094733/381aeb6a-042e-4dc3-8f9c-7d4a3cc391c8">

**Comment by StackOvertaken** [comment]
谢谢hooke，我是原来的求助人，[原贴在这里](https://meta.appinn.net/t/topic/53449/16)https://meta.appinn.net/t/topic/53449/16
最初的问题问题来在于很多网络和本地视频的画面比较灰暗。而我作为用户见过两种针对视频的增强技术。

其一是在10几年前像[迅雷影音](https://video.xunlei.com/pc.html)，暴风等国产视频播放器流行的画质增强功能，可以让一些场景灰暗的视频变正常，对枪版效果很好。
其二是 [游戏加加](https://gamepp.com/features.html) 的游戏滤镜功能，通过类似劫持Directx Overlay（描述可能有误，原谅我不太懂代码）来实时增强游戏图像，我不知道能不能用在浏览器视频上，或者其他视频播放器上。

对于视频增强功能
我个人感觉就是一个直方图均衡化（histogram equalization）的滤镜，证据在于下图: mpv播放时的截图用[xnview图片浏览器](https://www.xnview.com/en/) 的图像-调整-正常化 功能处理之后与"画质增强"的结果是一样的。

然后appinn的朋友帮我找到了ffmpeg的[正常化滤镜 vf=histeq=strength:intensity:antibanding，](https://ffmpeg.org/ffmpeg-filters.html#histeq)但是我试着使用之后效果不好，调不出"视频增强"或者xnview正常化的效果，可以看下面截图上的奇怪情况，这用的是vf=histeq=0.3:0.2:weak

希望能实现mpv达到迅雷影音的自动画质增强的效果
甚至是把滤镜直接挂到directx或者显卡驱动上，自动增强所有在播放的视频
以上

![正常化 PixPin_2024-03-06_05-37-05](https://github.com/natural-harmonia-gropius/mpv-config/assets/162375051/853cd5c0-2b98-4d47-a660-519baa7e4580)

**Comment by natural-harmonia-gropius** [comment]
我这里 xnview 的 normalize 的表现是保持最大动态范围的通道，拉伸其余的通道。对白平衡良好的图片没有区别。

![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/df67b6b5-9ef8-4e53-9129-788cba094be3)
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/c21eb064-9206-46f7-821a-2cae6066781e)
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/dcfcff3b-c91d-4644-975f-20291350c7a6)
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/62955a2c-1d40-4003-a1af-a8f10370e161)
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/23075392-5e96-4051-9f54-585bfc31b61a)
![image](https://github.com/natural-harmonia-gropius/mpv-config/assets/50797982/e1c8eda8-6e5f-4d68-a97c-17d83052cc66)

**Comment by natural-harmonia-gropius** [comment]
你试试这个着色器能不能满足需求，还要加上转换函数，目标色域 linear bt709/srgb。

```ini
glsl-shader=~~/shaders/hdr-toys/transfer-function/bt1886_inv.glsl
glsl-shader=~~/shaders/test.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/bt1886.glsl
```

```glsl
//!TEXTURE TONE
//!SIZE 1024 1
//!FORMAT rgba16f
//!FILTER LINEAR
//!BORDER REPEAT
//!STORAGE

//!HOOK OUTPUT
//!BIND HOOKED
//!BIND TONE
//!SAVE GARB
//!WIDTH 4096
//!HEIGHT 1
//!DESC bake lut

float bezier(float t, float a, float b, float c) {
    a = mix(a, b, t);
    b = mix(b, c, t);
    a = mix(a, b, t);
    return a;
}

vec2 bezier(float t, vec2 a, vec2 b, vec2 c) {
    return vec2(
        bezier(t, a.x, b.x, c.x),
        bezier(t, a.y, b.y, c.y)
    );
}

vec4 hook() {
    vec2 b = bezier(HOOKED_pos.x, vec2(0.0, 0.0), vec2(0.5, 0.8), vec2(1.0, 1.0));
    imageStore(TONE, ivec2(int(1023.0 * b.x), 0), vec4(vec3(b.y), 1.0));

    vec4 color = HOOKED_texOff(0);
    return color;
}

//!HOOK OUTPUT
//!BIND HOOKED
//!BIND TONE
//!DESC tone-mapping

float cbrt(float x) {
    return sign(x) * pow(abs(x), 1.0 / 3.0);
}

vec3 RGB_to_XYZ(vec3 RGB) {
    mat3 M = mat3(
        0.41239079926595934, 0.357584339383878,   0.1804807884018343,
        0.21263900587151027, 0.715168678767756,   0.07219231536073371,
        0.01933081871559182, 0.11919477979462598, 0.9505321522496607);
    return RGB * M;
}

vec3 XYZ_to_RGB(vec3 XYZ) {
    mat3 M = mat3(
         3.2409699419045226,  -1.537383177570094,   -0.4986107602930034,
        -0.9692436362808796,   1.8759675015077202,   0.04155505740717559,
         0.05563007969699366, -0.20397695888897652,  1.0569715142428786);
    return XYZ * M;
}

vec3 XYZ_to_LMS(vec3 XYZ) {
    mat3 M = mat3(
        0.8190224379967030, 0.3619062600528904, -0.1288737815209879,
        0.0329836539323885, 0.9292868615863434,  0.0361446663506424,
        0.0481771893596242, 0.2642395317527308,  0.6335478284694309);
    return XYZ * M;
}

vec3 LMS_to_XYZ(vec3 LMS) {
    mat3 M = mat3(
         1.2268798758459243, -0.5578149944602171,  0.2813910456659647,
        -0.0405757452148008,  1.1122868032803170, -0.0717110580655164,
        -0.0763729366746601, -0.4214933324022432,  1.5869240198367816);
    return LMS * M;
}

vec3 LMS_to_Lab(vec3 LMS) {
    mat3 M = mat3(
        0.2104542683093140,  0.7936177747023054, -0.0040720430116193,
        1.9779985324311684, -2.4285922420485799,  0.4505937096174110,
        0.0259040424655478,  0.7827717124575296, -0.8086757549230774);

    LMS = vec3(
        cbrt(LMS.x),
        cbrt(LMS.y),
        cbrt(LMS.z)
    );

    return LMS * M;
}

vec3 Lab_to_LMS(vec3 Lab) {
    mat3 M = mat3(
        1.0000000000000000,  0.3963377773761749,  0.2158037573099136,
        1.0000000000000000, -0.1055613458156586, -0.0638541728258133,
        1.0000000000000000, -0.0894841775298119, -1.2914855480194092);

    Lab = Lab * M;

    return vec3(
        pow(Lab.x, 3.0),
        pow(Lab.y, 3.0),
        pow(Lab.z, 3.0)
    );
}

float L_to_Lr(float x) {
    const float k1 = 0.206;
    const float k2 = 0.03;
    const float k3 = (1.0 + k1) / (1.0 + k2);
    return 0.5 * (k3 * x - k1 + sqrt(pow(k3 * x - k1, 2.0) + 4.0 * k2 * k3 * x));
}

float Lr_to_L(float x) {
    const float k1 = 0.206;
    const float k2 = 0.03;
    const float k3 = (1.0 + k1) / (1.0 + k2);
    return (x * (x + k1)) / (k3 * (x + k2));
}

vec3 RGB_to_Lab(vec3 color) {
    color   = RGB_to_XYZ(color);
    color   = XYZ_to_LMS(color);
    color   = LMS_to_Lab(color);
    color.x = L_to_Lr(color.x);
    return color;
}

vec3 Lab_to_RGB(vec3 color) {
    color.x = Lr_to_L(color.x);
    color   = Lab_to_LMS(color);
    color   = LMS_to_XYZ(color);
    color   = XYZ_to_RGB(color);
    return color;
}

float curve(float x) {
    // TODO: remove two compare
    if (x <= 1e-6)
        return 0.0;
    if (x >= 1.0 - 1e-6)
        return 1.0;
    return imageLoad(TONE, ivec2(int(1023.0 * x), 0)).x;
}

vec3 tone_mapping_ictcp(vec3 ICtCp) {
    float I2  = curve(ICtCp.x);
    ICtCp.yz *= max(ICtCp.x / I2, I2 / ICtCp.x);
    ICtCp.x   = I2;

    return ICtCp;
}

vec4 hook() {
    vec4 color = HOOKED_texOff(0);

    color.rgb = RGB_to_Lab(color.rgb);
    color.rgb = tone_mapping_ictcp(color.rgb);
    color.rgb = Lab_to_RGB(color.rgb);

    return color;
}
```

**Comment by StackOvertaken** [comment]
谢谢二位大佬，希望有更多的产品能集成画质增强功能😍
