### ISSUE TITLE
gamma 2.2和1886

### ISSUE THREAD

**Issue by HedioKojima** [natural-harmonia-gropius/mpv-config#31]
在校准的gamma为2.2的显示器上使用您的配置播放视频，视频大多为1886的gamma，会有什么影响吗？（我设置mpv的gamma为2.2后，差别肉眼感觉好像有一点，不是很清楚）

**Comment by natural-harmonia-gropius** [comment]
校准的话有 icc 用 `--icc-profile-auto`, 输入是 1886 输出是 2.2 暗部应该会比默认设置更黑一点

**Comment by HedioKojima** [comment]
谢谢您的及时回答，显示器自带的几个校准有2.2和1886的，您更推荐使用哪个呢？

**Comment by natural-harmonia-gropius** [comment]
用2.2, 有更准确的srgb用srgb, windows颜色默认srgb，全局1886桌面颜色会有点怪。另外由于一般观看环境比bt1886建议的环境亮，不设置 --target-trc=gamma2.2 可能更接近原始创作意图

**Comment by HedioKojima** [comment]
谢谢您的解惑
