### ISSUE TITLE
pressaction: don't clear osd messages

### ISSUE THREAD

**Issue by po5** [natural-harmonia-gropius/mpv-config#4]
Currently a hack is used to to clear osd messages generated by our commands, but that has the effect of prematurely clearing any osd messages that didn't come from the script.  
https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/scripts/pressaction.lua#L32
You can prepend `no-osd` to your commands to not display any osd messages, removing the need for this hack.

**Comment by natural-harmonia-gropius** [comment]
Done.
